# fly.toml app configuration file generated for sierra on 2024-03-31T14:24:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sierra'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1
